import type { Product } from '@/lib/types';

/* ─────────────────────────────────────────────
   Mock Product Data — Development only.
   All images point to real assets under:
     /public/images/sneakers/<slug>/

   Folder → image mapping:
   air-jordan-1-chicago   : side, back, top, sole, side_second, zoomedin, zoomin_otherside, box
   air-jordan-4-rm        : 1-8.webp
   air-jordan-40-infrared : 1-8.webp
   nike-air-max-1-86-og   : side, sole, topview, backview, otherside, backsidezoomin, zoomin, "another frontrightangle"
   nike-dunk-low-se-lny   : firstside, back, front, top, sole, otherside, frontmainlogo, frontzoomedview, secondzoomview, zoomview
   nike-pegasus-trail-5-gore-tex : 1-11.webp
   nike-vomero-18-gore-tex: 1-9.webp
   new-balance-550-golf-sl: side, otherside, backview, topview, toprightfront
   ───────────────────────────────────────────── */

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'jordan-1-chicago-2024',
    brand: 'Nike',
    model: 'Air Jordan 1 Retro High OG',
    colorway: 'Chicago',
    releaseYear: 2024,
    price: 420,
    condition: 'DS',
    availableSizes: [8, 9, 10, 11],
    totalPairsLeft: 1,
    heritage: 'The shoe that started a revolution. Banned by the NBA in 1985.',
    images: [
      { url: '/images/sneakers/air-jordan-1-chicago/side.webp',             alt: 'Air Jordan 1 Chicago lateral view',       isPrimary: true },
      { url: '/images/sneakers/air-jordan-1-chicago/side_second.webp',      alt: 'Air Jordan 1 Chicago medial view' },
      { url: '/images/sneakers/air-jordan-1-chicago/top.webp',              alt: 'Air Jordan 1 Chicago top view' },
      { url: '/images/sneakers/air-jordan-1-chicago/back.webp',             alt: 'Air Jordan 1 Chicago heel view' },
      { url: '/images/sneakers/air-jordan-1-chicago/sole.webp',             alt: 'Air Jordan 1 Chicago outsole' },
      { url: '/images/sneakers/air-jordan-1-chicago/zoomedin.webp',         alt: 'Air Jordan 1 Chicago detail close-up' },
      { url: '/images/sneakers/air-jordan-1-chicago/zoomin_otherside.webp', alt: 'Air Jordan 1 Chicago opposite side detail' },
      { url: '/images/sneakers/air-jordan-1-chicago/box.webp',              alt: 'Air Jordan 1 Chicago with box' },
    ],
  },
  {
    id: '2',
    slug: 'air-jordan-4-rm',
    brand: 'Nike',
    model: 'Air Jordan 4 RM',
    colorway: 'Black Canvas',
    releaseYear: 2024,
    price: 210,
    condition: 'DS',
    availableSizes: [7, 8, 9, 10, 11],
    totalPairsLeft: 6,
    heritage: 'The Jordan 4 Reconstructed — an entirely new construction of a classic silhouette.',
    images: [
      { url: '/images/sneakers/air-jordan-4-rm/1.webp', alt: 'Air Jordan 4 RM lateral view',      isPrimary: true },
      { url: '/images/sneakers/air-jordan-4-rm/2.webp', alt: 'Air Jordan 4 RM medial view' },
      { url: '/images/sneakers/air-jordan-4-rm/3.webp', alt: 'Air Jordan 4 RM top-down view' },
      { url: '/images/sneakers/air-jordan-4-rm/4.webp', alt: 'Air Jordan 4 RM heel detail' },
      { url: '/images/sneakers/air-jordan-4-rm/5.webp', alt: 'Air Jordan 4 RM sole view' },
      { url: '/images/sneakers/air-jordan-4-rm/6.webp', alt: 'Air Jordan 4 RM front view' },
      { url: '/images/sneakers/air-jordan-4-rm/7.webp', alt: 'Air Jordan 4 RM close-up' },
      { url: '/images/sneakers/air-jordan-4-rm/8.webp', alt: 'Air Jordan 4 RM lifestyle shot' },
    ],
  },
  {
    id: '3',
    slug: 'air-jordan-40-infrared',
    brand: 'Nike',
    model: 'Air Jordan 40',
    colorway: 'Infrared',
    releaseYear: 2024,
    price: 195,
    condition: 'DS',
    availableSizes: [8, 9, 10, 11, 12],
    totalPairsLeft: 9,
    heritage: 'The fortieth chapter — designed for the court but built for the culture.',
    images: [
      { url: '/images/sneakers/air-jordan-40-infrared/1.webp', alt: 'Air Jordan 40 Infrared lateral view',      isPrimary: true },
      { url: '/images/sneakers/air-jordan-40-infrared/2.webp', alt: 'Air Jordan 40 Infrared medial view' },
      { url: '/images/sneakers/air-jordan-40-infrared/3.webp', alt: 'Air Jordan 40 Infrared top-down view' },
      { url: '/images/sneakers/air-jordan-40-infrared/4.webp', alt: 'Air Jordan 40 Infrared heel detail' },
      { url: '/images/sneakers/air-jordan-40-infrared/5.webp', alt: 'Air Jordan 40 Infrared sole view' },
      { url: '/images/sneakers/air-jordan-40-infrared/6.webp', alt: 'Air Jordan 40 Infrared front view' },
      { url: '/images/sneakers/air-jordan-40-infrared/7.webp', alt: 'Air Jordan 40 Infrared close-up' },
      { url: '/images/sneakers/air-jordan-40-infrared/8.webp', alt: 'Air Jordan 40 Infrared lifestyle shot' },
    ],
  },
  {
    id: '4',
    slug: 'nike-air-max-1-86-og',
    brand: 'Nike',
    model: "Air Max 1 '86 OG G",
    colorway: 'Big Bubble',
    releaseYear: 2024,
    price: 160,
    condition: 'DS',
    availableSizes: [8, 8.5, 9, 9.5, 10, 11],
    totalPairsLeft: 5,
    heritage: "The original Air Max, faithfully reproduced with Tinker Hatfield's oversized Air unit.",
    images: [
      { url: '/images/sneakers/nike-air-max-1-86-og/side.webp',                    alt: "Air Max 1 '86 OG lateral view",        isPrimary: true },
      { url: '/images/sneakers/nike-air-max-1-86-og/otherside.webp',               alt: "Air Max 1 '86 OG medial view" },
      { url: '/images/sneakers/nike-air-max-1-86-og/topview.webp',                 alt: "Air Max 1 '86 OG top-down view" },
      { url: '/images/sneakers/nike-air-max-1-86-og/backview.webp',               alt: "Air Max 1 '86 OG heel view" },
      { url: '/images/sneakers/nike-air-max-1-86-og/sole.webp',                   alt: "Air Max 1 '86 OG outsole" },
      { url: '/images/sneakers/nike-air-max-1-86-og/zoomin.webp',                 alt: "Air Max 1 '86 OG detail close-up" },
      { url: '/images/sneakers/nike-air-max-1-86-og/backsidezoomin.webp',         alt: "Air Max 1 '86 OG heel close-up" },
      { url: '/images/sneakers/nike-air-max-1-86-og/another frontrightangle.webp', alt: "Air Max 1 '86 OG front-right angle" },
    ],
  },
  {
    id: '5',
    slug: 'nike-dunk-low-se-lny',
    brand: 'Nike',
    model: 'Dunk Low SE',
    colorway: 'Lunar New Year',
    releaseYear: 2024,
    price: 130,
    condition: 'DS',
    availableSizes: [7, 8, 9, 10, 11, 12],
    totalPairsLeft: 8,
    heritage: 'The court classic reimagined for the Lunar New Year — red and white for prosperity.',
    images: [
      { url: '/images/sneakers/nike-dunk-low-se-lny/firstside.webp',       alt: 'Dunk Low SE LNY lateral view',         isPrimary: true },
      { url: '/images/sneakers/nike-dunk-low-se-lny/otherside.webp',        alt: 'Dunk Low SE LNY medial view' },
      { url: '/images/sneakers/nike-dunk-low-se-lny/top.webp',              alt: 'Dunk Low SE LNY top-down view' },
      { url: '/images/sneakers/nike-dunk-low-se-lny/back.webp',             alt: 'Dunk Low SE LNY heel view' },
      { url: '/images/sneakers/nike-dunk-low-se-lny/sole.webp',             alt: 'Dunk Low SE LNY outsole' },
      { url: '/images/sneakers/nike-dunk-low-se-lny/front.webp',            alt: 'Dunk Low SE LNY front view' },
      { url: '/images/sneakers/nike-dunk-low-se-lny/frontmainlogo.webp',   alt: 'Dunk Low SE LNY Swoosh detail' },
      { url: '/images/sneakers/nike-dunk-low-se-lny/frontzoomedview.webp', alt: 'Dunk Low SE LNY front close-up' },
      { url: '/images/sneakers/nike-dunk-low-se-lny/zoomview.webp',        alt: 'Dunk Low SE LNY detail shot' },
      { url: '/images/sneakers/nike-dunk-low-se-lny/secondzoomview.webp',  alt: 'Dunk Low SE LNY secondary detail' },
    ],
  },
  {
    id: '6',
    slug: 'nike-pegasus-trail-5-gore-tex',
    brand: 'Nike',
    model: 'Pegasus Trail 5 GORE-TEX',
    colorway: 'Midnight Navy',
    releaseYear: 2024,
    price: 160,
    condition: 'DS',
    availableSizes: [8, 9, 10, 11],
    totalPairsLeft: 4,
    heritage: 'Weatherproof trail runner built on the Pegasus platform — for the committed runner.',
    images: [
      { url: '/images/sneakers/nike-pegasus-trail-5-gore-tex/1.webp',  alt: 'Pegasus Trail 5 GTX lateral view',      isPrimary: true },
      { url: '/images/sneakers/nike-pegasus-trail-5-gore-tex/2.webp',  alt: 'Pegasus Trail 5 GTX medial view' },
      { url: '/images/sneakers/nike-pegasus-trail-5-gore-tex/3.webp',  alt: 'Pegasus Trail 5 GTX top-down view' },
      { url: '/images/sneakers/nike-pegasus-trail-5-gore-tex/4.webp',  alt: 'Pegasus Trail 5 GTX heel view' },
      { url: '/images/sneakers/nike-pegasus-trail-5-gore-tex/5.webp',  alt: 'Pegasus Trail 5 GTX sole view' },
      { url: '/images/sneakers/nike-pegasus-trail-5-gore-tex/6.webp',  alt: 'Pegasus Trail 5 GTX front view' },
      { url: '/images/sneakers/nike-pegasus-trail-5-gore-tex/7.webp',  alt: 'Pegasus Trail 5 GTX lifestyle close-up' },
      { url: '/images/sneakers/nike-pegasus-trail-5-gore-tex/8.webp',  alt: 'Pegasus Trail 5 GTX detail shot' },
      { url: '/images/sneakers/nike-pegasus-trail-5-gore-tex/9.webp',  alt: 'Pegasus Trail 5 GTX brand detail' },
      { url: '/images/sneakers/nike-pegasus-trail-5-gore-tex/10.webp', alt: 'Pegasus Trail 5 GTX GORE-TEX tag' },
      { url: '/images/sneakers/nike-pegasus-trail-5-gore-tex/11.webp', alt: 'Pegasus Trail 5 GTX outsole tread' },
    ],
  },
  {
    id: '7',
    slug: 'nike-vomero-18-gore-tex',
    brand: 'Nike',
    model: 'Vomero 18 GORE-TEX',
    colorway: 'Pure Platinum',
    releaseYear: 2024,
    price: 175,
    condition: 'DS',
    availableSizes: [8, 9, 10, 11, 12],
    totalPairsLeft: 7,
    heritage: 'Maximum cushioned road runner with full GORE-TEX lining for all-weather confidence.',
    images: [
      { url: '/images/sneakers/nike-vomero-18-gore-tex/1.webp', alt: 'Vomero 18 GTX lateral view',      isPrimary: true },
      { url: '/images/sneakers/nike-vomero-18-gore-tex/2.webp', alt: 'Vomero 18 GTX medial view' },
      { url: '/images/sneakers/nike-vomero-18-gore-tex/3.webp', alt: 'Vomero 18 GTX top-down view' },
      { url: '/images/sneakers/nike-vomero-18-gore-tex/4.webp', alt: 'Vomero 18 GTX heel view' },
      { url: '/images/sneakers/nike-vomero-18-gore-tex/5.webp', alt: 'Vomero 18 GTX sole view' },
      { url: '/images/sneakers/nike-vomero-18-gore-tex/6.webp', alt: 'Vomero 18 GTX front view' },
      { url: '/images/sneakers/nike-vomero-18-gore-tex/7.webp', alt: 'Vomero 18 GTX lifestyle close-up' },
      { url: '/images/sneakers/nike-vomero-18-gore-tex/8.webp', alt: 'Vomero 18 GTX detail shot' },
      { url: '/images/sneakers/nike-vomero-18-gore-tex/9.webp', alt: 'Vomero 18 GTX outsole tread' },
    ],
  },
  {
    id: '8',
    slug: 'new-balance-550-golf-sl',
    brand: 'New Balance',
    model: '550 Golf SL',
    colorway: 'White Navy',
    releaseYear: 2024,
    price: 120,
    condition: 'DS',
    availableSizes: [8, 8.5, 9, 9.5, 10, 11],
    totalPairsLeft: 10,
    heritage: 'The court silhouette meets the fairway — a golf-ready 550 with spikeless outsole.',
    images: [
      { url: '/images/sneakers/new-balance-550-golf-sl/side.webp',          alt: 'New Balance 550 Golf SL lateral view',     isPrimary: true },
      { url: '/images/sneakers/new-balance-550-golf-sl/otherside.webp',     alt: 'New Balance 550 Golf SL medial view' },
      { url: '/images/sneakers/new-balance-550-golf-sl/backview.webp',      alt: 'New Balance 550 Golf SL heel view' },
      { url: '/images/sneakers/new-balance-550-golf-sl/topview.webp',      alt: 'New Balance 550 Golf SL top-down view' },
      { url: '/images/sneakers/new-balance-550-golf-sl/toprightfront.webp', alt: 'New Balance 550 Golf SL front-right angle' },
    ],
  },
];

/** Featured drop mock */
export const MOCK_FEATURED_DROP = {
  productName: 'Air Jordan 1 Retro High OG',
  colorway: "'Chicago' 2024",
  dropAt: new Date(Date.now() + 86400 * 2 * 1000 + 3600 * 4 * 1000).toISOString(),
  totalQty: 36,
  price: 420,
  slug: 'jordan-1-chicago-2024',
  imageUrl: '/images/sneakers/air-jordan-1-chicago/back.webp',
};
